from .base import *
import os

DEBUG = False

STATIC_ROOT = os.getenv('UUBLOOMINGTON_STATIC_ROOT')

MEDIA_ROOT = os.getenv('UUBLOOMINGTON_MEDIA_ROOT')

SECRET_KEY = os.getenv('UUBLOOMINGTON_SECRET_KEY')

PLANNING_CENTER_APPLICATION_ID = os.getenv("UUBLOOMINGTON_PLANNING_CENTER_APPLICATION_ID")
PLANNING_CENTER_SECRET = os.getenv("UUBLOOMINGTON_PLANNING_CENTER_SECRET")

try:
    from .local import *
except ImportError:
    pass
