# Generated by Django 5.1.4 on 2025-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planningcenter_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_must_contain', models.CharField(blank=True, help_text='Only show events which contain this text in their description. Leave blank to show all events.', max_length=255, null=True)),
                ('show_next_events', models.IntegerField(default=15, help_text='Show this number of events which match the filter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
