# Generated by Django 5.1 on 2025-02-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planningcenter_events", "0003_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlisting",
            name="show_next_events",
            field=models.IntegerField(
                default=15,
                help_text="Show this number of events which match the filter.",
            ),
        ),
    ]
