# Generated by Django 5.1 on 2025-02-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planningcenter_events", "0004_alter_eventlisting_show_next_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("start_time",)},
        ),
    ]
