# Generated by Django 4.1.6 on 2023-04-24 20:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_publish_in_newsletter'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('issue', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='newsletter.issue')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.post')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
