# Generated by Django 4.1.6 on 2023-04-24 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_issuesegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='posts',
        ),
        migrations.AddField(
            model_name='issue',
            name='publication_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
    ]
