# Generated by Django 4.2.1 on 2023-07-28 01:38

import core.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('newsletter', '0004_alter_issuesegment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('read_more', core.blocks.ReadMoreTagBlock()), ('show_featured_image', core.blocks.ShowFeaturedImageBlock()), ('page_feature', core.blocks.PageFeatureBlock()), ('expandable_list', wagtail.blocks.ListBlock(core.blocks.ExpandableListItemBlock)), ('embed', wagtail.embeds.blocks.EmbedBlock(max_height=900)), ('selectable_index', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock())])), ('badge_area', core.blocks.BadgeAreaBlock(child_block=wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock()), ('link_text', wagtail.blocks.CharBlock())]))), ('anchor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='IssueSegment',
        ),
    ]
