# Generated by Django 4.2.1 on 2023-07-28 02:01

import core.blocks
from django.db import migrations, models
import django.db.models.deletion
import newsletter.blocks
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_standardblockpage_body'),
        ('newsletter', '0005_issue_body_issue_featured_image_delete_issuesegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('standardblockpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.standardblockpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.standardblockpage',),
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='description',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('read_more', core.blocks.ReadMoreTagBlock()), ('show_featured_image', core.blocks.ShowFeaturedImageBlock()), ('page_feature', core.blocks.PageFeatureBlock()), ('expandable_list', wagtail.blocks.ListBlock(core.blocks.ExpandableListItemBlock)), ('embed', wagtail.embeds.blocks.EmbedBlock(max_height=900)), ('selectable_index', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock())])), ('badge_area', core.blocks.BadgeAreaBlock(child_block=wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock()), ('link_text', wagtail.blocks.CharBlock())]))), ('anchor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('read_more', core.blocks.ReadMoreTagBlock()), ('show_featured_image', core.blocks.ShowFeaturedImageBlock()), ('page_feature', core.blocks.PageFeatureBlock()), ('expandable_list', wagtail.blocks.ListBlock(core.blocks.ExpandableListItemBlock)), ('embed', wagtail.embeds.blocks.EmbedBlock(max_height=900)), ('selectable_index', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock())])), ('badge_area', core.blocks.BadgeAreaBlock(child_block=wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock()), ('link_text', wagtail.blocks.CharBlock())]))), ('anchor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock())])), ('article', newsletter.blocks.ArticleBlock())], null=True, use_json_field=True),
        ),
    ]
