# Generated by Django 5.1 on 2024-11-27 17:40

import core.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0008_alter_issue_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("read_more", 1),
                    ("show_featured_image", 2),
                    ("page_feature", 3),
                    ("expandable_list", 4),
                    ("embed", 5),
                    ("selectable_index", 7),
                    ("badge_area", 12),
                    ("anchor", 13),
                    ("article", 14),
                    ("table_of_contents", 15),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("core.blocks.ReadMoreTagBlock", (), {}),
                    2: ("core.blocks.ShowFeaturedImageBlock", (), {}),
                    3: ("core.blocks.PageFeatureBlock", (), {}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (core.blocks.ExpandableListItemBlock,),
                        {},
                    ),
                    5: ("wagtail.embeds.blocks.EmbedBlock", (), {"max_height": 900}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {}),
                    7: ("wagtail.blocks.StructBlock", [[("page", 6)]], {}),
                    8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    9: ("wagtail.blocks.URLBlock", (), {}),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("link", 9), ("link_text", 10)]],
                        {},
                    ),
                    12: ("core.blocks.BadgeAreaBlock", (11,), {}),
                    13: ("wagtail.blocks.StructBlock", [[("name", 10)]], {}),
                    14: ("newsletter.blocks.ArticleBlock", (), {}),
                    15: ("newsletter.blocks.TableOfContentsBlock", (), {}),
                },
                default=[("show_featured_image", None), ("table_of_contents", None)],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("read_more", 1),
                    ("show_featured_image", 2),
                    ("page_feature", 3),
                    ("expandable_list", 4),
                    ("embed", 5),
                    ("selectable_index", 7),
                    ("badge_area", 12),
                    ("anchor", 13),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("core.blocks.ReadMoreTagBlock", (), {}),
                    2: ("core.blocks.ShowFeaturedImageBlock", (), {}),
                    3: ("core.blocks.PageFeatureBlock", (), {}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (core.blocks.ExpandableListItemBlock,),
                        {},
                    ),
                    5: ("wagtail.embeds.blocks.EmbedBlock", (), {"max_height": 900}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {}),
                    7: ("wagtail.blocks.StructBlock", [[("page", 6)]], {}),
                    8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    9: ("wagtail.blocks.URLBlock", (), {}),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("link", 9), ("link_text", 10)]],
                        {},
                    ),
                    12: ("core.blocks.BadgeAreaBlock", (11,), {}),
                    13: ("wagtail.blocks.StructBlock", [[("name", 10)]], {}),
                },
                null=True,
            ),
        ),
    ]
