# Generated by Django 4.1.6 on 2023-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='vimeo_link',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
