# Generated by Django 4.1.6 on 2023-03-03 19:15

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicepage_vimeo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='vimeo_link',
            field=models.CharField(default=services.models.get_default_stream_url, max_length=100, null=True),
        ),
    ]
