# Generated by Django 4.1.6 on 2023-04-25 20:55

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('services', '0004_alter_servicepage_vimeo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceshomepage',
            name='service_schedule',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
        migrations.AddField(
            model_name='serviceshomepage',
            name='service_time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='OrderOfService',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_service', to='services.servicepage', unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
