# Generated by Django 4.1.6 on 2023-04-28 14:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceshomepage_service_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofservice',
            name='program',
            field=wagtail.fields.StreamField([('element', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('participants', wagtail.blocks.StreamBlock([('person', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.TextBlock())])), ('body', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=None),
        ),
    ]
