# Generated by Django 4.1.6 on 2023-05-01 13:27

from django.db import migrations
import services.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_orderofservice_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='program',
            field=wagtail.fields.StreamField([('element', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('info', wagtail.blocks.StreamBlock([('person', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.TextBlock())], required=False))])), ('text', wagtail.blocks.RichTextBlock()), ('multicolumn', wagtail.blocks.StructBlock([('column', wagtail.blocks.ListBlock(services.blocks.OOSGenericStreamBlock))]))], null=True, use_json_field=None),
        ),
    ]
