# Generated by Django 4.1.6 on 2023-05-01 14:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_orderofservice_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='program',
            field=wagtail.fields.StreamField([('element', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('info', wagtail.blocks.StreamBlock([('text', wagtail.blocks.TextBlock())], required=False))])), ('text', wagtail.blocks.RichTextBlock()), ('multicolumn', wagtail.blocks.StreamBlock([('column', wagtail.blocks.StreamBlock([('body', wagtail.blocks.RichTextBlock())]))]))], null=True, use_json_field=None),
        ),
    ]
