# Generated by Django 4.1.6 on 2023-05-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_orderofservice_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='order_of_service_link',
        ),
    ]
