# Generated by Django 4.1.6 on 2023-05-01 14:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_servicepage_order_of_service_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='program',
            field=wagtail.fields.StreamField([('element', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('info', wagtail.blocks.StreamBlock([('text', wagtail.blocks.TextBlock())], required=False))])), ('text', wagtail.blocks.RichTextBlock()), ('multicolumn', wagtail.blocks.StreamBlock([('column', wagtail.blocks.StreamBlock([('body', wagtail.blocks.RichTextBlock())]))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_of_service', to='services.servicepage'),
        ),
    ]
