# Generated by Django 4.2.1 on 2023-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicepage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='one_sentence',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
