# Generated by Django 4.2.1 on 2023-05-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicepage_one_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_of_service', to='services.servicepage', unique=True),
        ),
    ]
