# Generated by Django 4.2.1 on 2023-05-21 01:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_servicepage_one_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='program',
            field=wagtail.fields.StreamField([('element', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('info', wagtail.blocks.RichTextBlock(required=False))])), ('text', wagtail.blocks.RichTextBlock()), ('multicolumn', wagtail.blocks.StreamBlock([('column', wagtail.blocks.StreamBlock([('body', wagtail.blocks.RichTextBlock())]))]))], null=True, use_json_field=True),
        ),
    ]
