# Generated by Django 4.2.1 on 2023-05-22 16:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_orderofservice_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofservice',
            name='back_page',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='cover_page',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
