# Generated by Django 4.2.1 on 2023-05-25 23:52

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_orderofservice_back_page_orderofservice_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='back_page',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='cover_page',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
