# Generated by Django 4.2.1 on 2023-05-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_orderofservice_back_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='video_archive_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
