# Generated by Django 4.2.5 on 2023-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_servicepage_video_archive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='show_video_embed',
            field=models.BooleanField(default=True),
        ),
    ]
