# Generated by Django 5.1 on 2024-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_alter_servicepage_vimeo_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderofservice",
            name="back_page_header",
            field=models.CharField(
                default="Other Sunday Information",
                help_text='This will be the title of the "back page" tab on the service page.',
                max_length=255,
            ),
        ),
    ]
