# Generated by Django 5.1 on 2024-11-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0022_orderofservice_back_page_header"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderofservice",
            old_name="back_page_header",
            new_name="back_page_title",
        ),
    ]
