# Generated by Django 5.1 on 2025-01-03 18:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0023_rename_back_page_header_orderofservice_back_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceshomepage",
            name="no_services_placeholder",
            field=wagtail.fields.RichTextField(
                help_text="Text to display if no future services exist", null=True
            ),
        ),
    ]
