# Generated by Django 5.1 on 2025-03-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0023_rename_back_page_header_orderofservice_back_page_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderofservice",
            name="time",
        ),
        migrations.RemoveField(
            model_name="serviceshomepage",
            name="service_time",
        ),
    ]
