# Generated by Django 5.1 on 2025-03-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_serviceshomepage_no_services_placeholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceshomepage",
            name="no_services_placeholder",
        ),
    ]
