# Generated by Django 5.1 on 2025-03-03 23:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_serviceshomepage_order_of_service_program_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceshomepage",
            name="order_of_service_program_template",
            field=wagtail.fields.StreamField(
                [("element", 2), ("text", 3), ("multicolumn", 5)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("header", 0), ("info", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: ("wagtail.blocks.StreamBlock", [[("body", 3)]], {}),
                    5: ("wagtail.blocks.StreamBlock", [[("column", 4)]], {}),
                },
                help_text="Newly-created Order of Service pages will contain this in their Program field.",
                null=True,
                verbose_name="Order of Service Program Template",
            ),
        ),
    ]
