# Generated by Django 5.1 on 2025-03-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_remove_serviceshomepage_no_services_placeholder"),
        ("services", "0026_alter_serviceshomepage_order_of_service_program_template"),
    ]

    operations = []
