# Generated by Django 5.1 on 2025-03-05 16:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_merge_20250304_1825"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="transcript",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
