# Generated by Django 5.1 on 2025-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_servicepage_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="transcript_heading",
            field=models.CharField(default="Sermon Transcript", max_length=200),
        ),
    ]
