# Generated by Django 5.1 on 2025-03-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0029_servicepage_transcript_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepage",
            name="vimeo_link",
        ),
    ]
