# Generated by Django 5.1 on 2025-03-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0030_remove_servicepage_vimeo_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
