# Generated by Django 5.1 on 2025-04-16 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0031_delete_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceshomepage",
            name="service_archive_start",
            field=models.DateField(
                default=datetime.date(1, 1, 1),
                help_text="Don't show any services older than this date in the paginated archive.",
                verbose_name="Service Archive Start Date",
            ),
        ),
        migrations.AddField(
            model_name="serviceshomepage",
            name="services_per_page",
            field=models.IntegerField(
                default=15,
                help_text="Display this many archived services per page.",
                verbose_name="Services per Page",
            ),
        ),
    ]
