# Generated by Django 5.1 on 2025-05-28 17:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0032_serviceshomepage_service_archive_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="one_sentence",
            field=wagtail.fields.RichTextField(max_length=300, null=True),
        ),
    ]
