# Generated by Django 5.1 on 2025-05-28 19:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0033_alter_servicepage_one_sentence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="one_sentence",
            field=wagtail.fields.RichTextField(
                help_text="A shortened description of the service, displayed on the home page. Needs to be extremely short when also using a featured image.",
                null=True,
                verbose_name="Short Description",
            ),
        ),
    ]
