# Generated by Django 5.1 on 2025-05-28 19:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0034_alter_servicepage_one_sentence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
