# Generated by Django 5.2.3 on 2025-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0036_rename_one_sentence_servicepage_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="transcript_heading",
            field=models.CharField(default="Sermon Text", max_length=200),
        ),
    ]
