# Generated by Django 5.2.3 on 2025-06-26 19:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0037_alter_servicepage_transcript_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderofservice",
            name="back_page_description",
            field=wagtail.fields.RichTextField(
                default="Information about other happenings at UUCB each week is available here.",
                help_text='This will be the short description of the "back page" tab on the service page, displayed just under the title.',
            ),
        ),
    ]
