# Generated by Django 5.2.3 on 2026-01-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0038_orderofservice_back_page_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="homepage_location_text",
            field=models.CharField(default="or in person!", max_length=200),
        ),
    ]
