# Generated by Django 6.0.3 on 2026-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_servicepage_homepage_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='livestream_available',
            field=models.BooleanField(default=True),
        ),
    ]
