# Generated by Django 6.0.3 on 2026-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_servicepage_livestream_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='livestream_available',
            field=models.BooleanField(default=True, help_text='If you uncheck this, be sure to also change the homepage location text.'),
        ),
    ]
