# Generated by Django 5.0.2 on 2024-05-29 14:19

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvancedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("send_confirmation", models.BooleanField(default=False)),
                (
                    "notification_email",
                    models.CharField(
                        blank=True,
                        help_text="Enter email addresses to notify of submissions to this form, separated by commas.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "form_fields",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", wagtail.blocks.RichTextBlock()),
                            (
                                "single_line_text_field",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("label_text", wagtail.blocks.CharBlock()),
                                        (
                                            "placeholder_text",
                                            wagtail.blocks.CharBlock(),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvancedFormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitter_name", models.CharField(max_length=500)),
                ("submitter_email", models.EmailField(max_length=254)),
                ("response_json", models.JSONField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="advanced_forms.advancedform",
                    ),
                ),
            ],
        ),
    ]
