# Generated by Django 5.1 on 2024-08-19 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advanced_forms", "0002_advancedform_confirmation_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedformresponse",
            name="submit_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
