# Generated by Django 5.1 on 2024-08-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advanced_forms", "0003_advancedformresponse_submit_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advancedformresponse",
            old_name="submit_date",
            new_name="submission_datetime",
        ),
    ]
