# Generated by Django 5.1.4 on 2025-04-29 17:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_forms', '0004_rename_submit_date_advancedformresponse_submission_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedform',
            name='form_fields',
            field=wagtail.fields.StreamField([('single_line_text_field', 3), ('telephone_input_field', 3), ('email_input_field', 3), ('checkboxes_field', 5), ('radio_buttons_field', 5), ('dropdown_field', 5), ('multi_line_text_field', 3), ('rich_text', 6), ('repeating_fields', 8), ('submitter_name_field', 10), ('submitter_email_field', 13)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label_text', 0), ('placeholder_text', 1), ('name_slug', 1), ('required', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (0,), {}), 5: ('wagtail.blocks.StructBlock', [[('label_text', 0), ('name_slug', 1), ('options', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StreamBlock', [[('single_line_text_field', 3), ('telephone_input_field', 3), ('email_input_field', 3), ('rich_text', 6), ('checkboxes_field', 5), ('radio_buttons_field', 5), ('dropdown_field', 5), ('multi_line_text_field', 3)]], {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('fields', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Your Name'}), 10: ('wagtail.blocks.StructBlock', [[('label_text', 9), ('placeholder_text', 1)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Your Email Address'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'you@example.com', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('label_text', 11), ('placeholder_text', 12)]], {})}),
        ),
    ]
