# Generated by Django 5.2.5 on 2025-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_forms', '0007_alter_advancedform_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedformresponse',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advancedformresponse',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
