# Generated by Django 5.2.5 on 2025-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_forms', '0008_alter_advancedformresponse_submitter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedformresponse',
            name='submitter_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advancedformresponse',
            name='submitter_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
