# Generated by Django 5.2.3 on 2025-07-03 18:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("kiosk_content", 6)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Shown on the kiosk front page."},
                            ),
                            3: (
                                "wagtail.blocks.StreamBlock",
                                [[]],
                                {
                                    "blocks": [],
                                    "help_text": "Shown when this content is selected on the kiosk",
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "If not empty, overrides the Details field with the body of the selected page",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail_color_panel.blocks.NativeColorBlock",
                                (),
                                {
                                    "default": "#006b1b",
                                    "help_text": "Accent color for this content. Primarily used for borders.",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("featured_image", 1),
                                        ("one_sentence", 2),
                                        ("details", 3),
                                        ("details_page", 4),
                                        ("accent_color", 5),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "sidebar",
                    wagtail.fields.StreamField(
                        [("rich_text", 0)],
                        block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})},
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
