# Generated by Django 5.2.3 on 2025-07-25 04:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0003_alter_kioskpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kioskpage",
            name="sidebar",
            field=wagtail.fields.StreamField(
                [("kiosk_sidebar", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 2), ("image", 1)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("featured_image", 1), ("body", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
