# Generated by Django 5.2.3 on 2025-09-24 13:47

import advanced_forms.models
import core.blocks
import planningcenter_events.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0005_alter_kioskpage_body_alter_kioskpage_sidebar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kioskpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("kiosk_content", 45)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Shown on the kiosk front page."},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: ("core.blocks.ReadMoreTagBlock", (), {}),
                    5: ("core.blocks.ShowFeaturedImageBlock", (), {}),
                    6: ("core.blocks.PageFeatureBlock", (), {}),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (core.blocks.ExpandableListItemBlock,),
                        {},
                    ),
                    8: ("wagtail.embeds.blocks.EmbedBlock", (), {"max_height": 900}),
                    9: ("core.blocks.AutoIndexBlock", (), {}),
                    10: ("wagtail.blocks.PageChooserBlock", (), {}),
                    11: ("wagtail.blocks.StructBlock", [[("page", 10)]], {}),
                    12: ("core.blocks.DocumentListBlock", (), {}),
                    13: ("wagtail.blocks.URLBlock", (), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("link", 13), ("link_text", 0)]],
                        {},
                    ),
                    15: ("core.blocks.BadgeAreaBlock", (14,), {}),
                    16: ("wagtail.blocks.StructBlock", [[("name", 0)]], {}),
                    17: ("core.blocks.UpcomingServiceBlock", (), {}),
                    18: ("core.blocks.UpcomingOrderOfServiceBlock", (), {}),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 3)]],
                        {"max_num": 3},
                    ),
                    20: ("wagtail.blocks.StreamBlock", [[("column", 19)]], {}),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Image associated with step in directions",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 3), ("image", 21)]],
                        {},
                    ),
                    23: ("wagtail.blocks.StreamBlock", [[("step", 22)]], {}),
                    24: (
                        "core.blocks.AdvancedFormBlock",
                        (advanced_forms.models.AdvancedForm,),
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("body", 3),
                                ("image", 1),
                                ("action_text", 0),
                                ("action_link", 0),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"default": "Show More"}),
                    27: ("wagtail.blocks.CharBlock", (), {"default": "Show Less"}),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 3),
                                ("page_feature", 6),
                                ("embed", 8),
                                ("auto_index", 9),
                                ("selectable_index", 11),
                                ("document_list", 12),
                                ("badge_area", 15),
                                ("anchor", 16),
                                ("upcoming_service", 17),
                                ("upcoming_oos", 18),
                                ("multi_column", 20),
                                ("directions", 23),
                                ("page_tree_index", 11),
                                ("advanced_form", 24),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("body", 3),
                                ("image", 1),
                                ("expand_action_text", 26),
                                ("contract_action_text", 27),
                                ("expanded_content", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.StreamBlock",
                        [[("card", 25), ("expandable_card", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 3),
                                ("read_more", 4),
                                ("show_featured_image", 5),
                                ("page_feature", 6),
                                ("expandable_list", 7),
                                ("embed", 8),
                                ("auto_index", 9),
                                ("selectable_index", 11),
                                ("document_list", 12),
                                ("badge_area", 15),
                                ("anchor", 16),
                                ("upcoming_service", 17),
                                ("upcoming_oos", 18),
                                ("multi_column", 20),
                                ("directions", 23),
                                ("page_tree_index", 11),
                                ("advanced_form", 24),
                                ("card_container", 30),
                            ]
                        ],
                        {"required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("body", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 3),
                                ("read_more", 4),
                                ("show_featured_image", 5),
                                ("page_feature", 6),
                                ("expandable_list", 7),
                                ("embed", 8),
                                ("auto_index", 9),
                                ("selectable_index", 11),
                                ("document_list", 12),
                                ("badge_area", 15),
                                ("anchor", 16),
                                ("upcoming_service", 17),
                                ("upcoming_oos", 18),
                                ("multi_column", 20),
                                ("directions", 23),
                                ("page_tree_index", 11),
                                ("advanced_form", 24),
                                ("card_container", 30),
                                ("sub_sub_section", 32),
                            ]
                        ],
                        {"required": False},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("body", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 3),
                                ("read_more", 4),
                                ("show_featured_image", 5),
                                ("page_feature", 6),
                                ("expandable_list", 7),
                                ("embed", 8),
                                ("auto_index", 9),
                                ("selectable_index", 11),
                                ("document_list", 12),
                                ("badge_area", 15),
                                ("anchor", 16),
                                ("upcoming_service", 17),
                                ("upcoming_oos", 18),
                                ("multi_column", 20),
                                ("directions", 23),
                                ("page_tree_index", 11),
                                ("advanced_form", 24),
                                ("card_container", 30),
                                ("sub_section", 34),
                            ]
                        ],
                        {"required": False},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("body", 35)]],
                        {},
                    ),
                    37: ("core.blocks.TableOfContentsBlock", (), {}),
                    38: (
                        "planningcenter_events.blocks.EventListingBlock",
                        (planningcenter_events.models.EventListing,),
                        {},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 3),
                                ("read_more", 4),
                                ("show_featured_image", 5),
                                ("page_feature", 6),
                                ("expandable_list", 7),
                                ("embed", 8),
                                ("auto_index", 9),
                                ("selectable_index", 11),
                                ("document_list", 12),
                                ("badge_area", 15),
                                ("anchor", 16),
                                ("upcoming_service", 17),
                                ("upcoming_oos", 18),
                                ("multi_column", 20),
                                ("directions", 23),
                                ("page_tree_index", 11),
                                ("advanced_form", 24),
                                ("card_container", 30),
                                ("section", 36),
                                ("table_of_contents", 37),
                                ("event_listing", 38),
                            ]
                        ],
                        {
                            "help_text": "Shown when this content is selected on the kiosk",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "If not empty, overrides the Details field with the body of the selected page",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail_color_panel.blocks.NativeColorBlock",
                        (),
                        {
                            "default": "#006b1b",
                            "help_text": "Accent color for this content. Primarily used for borders.",
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of an icon to accompany this action link. Valid icon names can be found at feathericons.com."
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("url", 13), ("icon", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.StreamBlock",
                        [[("details_action", 43)]],
                        {
                            "help_text": "Action links shown at the top of the details modal.",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("featured_image", 1),
                                ("one_sentence", 2),
                                ("details", 39),
                                ("details_page", 40),
                                ("accent_color", 41),
                                ("actions", 44),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
