# Generated by Django 4.1.6 on 2023-03-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
        ('core', '0002_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_in_newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='newsletter.newsletter'),
        ),
    ]
