# Generated by Django 4.1.6 on 2023-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pagewithposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagewithposts',
            name='show_posts',
            field=models.BooleanField(default=True),
        ),
    ]
