# Generated by Django 4.2.1 on 2023-05-22 22:39

import core.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_listpageitem_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpageitem',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('read_more', core.blocks.ReadMoreTagBlock())], null=True, use_json_field=True),
        ),
    ]
