# Generated by Django 4.2.1 on 2023-05-24 15:48

import core.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('core', '0010_listpageitem_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardBlockPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('read_more', core.blocks.ReadMoreTagBlock()), ('show_featured_image', core.blocks.ShowFeaturedImageBlock())], null=True, use_json_field=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
