# Generated by Django 4.2.5 on 2023-10-11 01:17

import core.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_standardblockpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardblockpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('read_more', core.blocks.ReadMoreTagBlock()), ('show_featured_image', core.blocks.ShowFeaturedImageBlock()), ('page_feature', core.blocks.PageFeatureBlock()), ('expandable_list', wagtail.blocks.ListBlock(core.blocks.ExpandableListItemBlock)), ('embed', wagtail.embeds.blocks.EmbedBlock(max_height=900)), ('auto_index', core.blocks.AutoIndexBlock()), ('selectable_index', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock())])), ('document_list', core.blocks.DocumentListBlock()), ('badge_area', core.blocks.BadgeAreaBlock(child_block=wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock()), ('link_text', wagtail.blocks.CharBlock())]))), ('anchor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock())])), ('upcoming_service', core.blocks.UpcomingServiceBlock()), ('multi_column', wagtail.blocks.StreamBlock([('column', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock())], max_num=3))]))], null=True, use_json_field=True),
        ),
    ]
