# Generated by Django 5.0 on 2024-01-16 20:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_formpage_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('check_field', models.CharField(max_length=50, null=True)),
                ('field', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_conditions', to='core.formfield')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
