# Generated by Django 5.0 on 2024-02-02 19:54

import core.blocks
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_formpage_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardblockpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('read_more', core.blocks.ReadMoreTagBlock()), ('show_featured_image', core.blocks.ShowFeaturedImageBlock()), ('page_feature', core.blocks.PageFeatureBlock()), ('expandable_list', wagtail.blocks.ListBlock(core.blocks.ExpandableListItemBlock)), ('embed', wagtail.embeds.blocks.EmbedBlock(max_height=900)), ('auto_index', core.blocks.AutoIndexBlock()), ('selectable_index', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock())])), ('document_list', core.blocks.DocumentListBlock()), ('badge_area', core.blocks.BadgeAreaBlock(child_block=wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock()), ('link_text', wagtail.blocks.CharBlock())]))), ('anchor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock())])), ('upcoming_service', core.blocks.UpcomingServiceBlock()), ('upcoming_oos', core.blocks.UpcomingOrderOfServiceBlock()), ('multi_column', wagtail.blocks.StreamBlock([('column', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock())], max_num=3))])), ('directions', wagtail.blocks.StreamBlock([('step', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image associated with step in directions', required=False))]))]))], null=True, use_json_field=True),
        ),
    ]
