# Generated by Django 5.0.2 on 2024-02-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    # replaces = [('core', '0024_formpage_confirmation_email_ending_and_more'), ('core', '0025_formpage_email_field_name_formpage_name_field_name'), ('core', '0026_alter_formpage_email_field_name_and_more'), ('core', '0027_alter_formpage_confirmation_email_ending_and_more'), ('core', '0028_alter_formpage_confirmation_email_ending_and_more')]

    dependencies = [
        ('core', '0023_alter_standardblockpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=False, help_text="\n        If checked, this form will send a confirmation to the submitter.\n        For this to work, your form MUST contain required fields for the submitter's name and email,\n        and those fields must be specified below. \n        "),
        ),
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_ending',
            field=models.TextField(blank=True, help_text='\n        Text to place at the end of the confirmation email, after the submitted data\n        ', null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_greeting',
            field=models.TextField(blank=True, help_text='\n        Text to place at the beginning of the confirmation email, before the submitted data\n        ', null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='email_field_name',
            field=models.CharField(blank=True, default='email', help_text="\n        The name of the field representing the submitter's email address\n        ", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='name_field_name',
            field=models.CharField(blank=True, default='name', help_text='\n        The name of the field representing "name" for email purposes (usually where the submitter enters their name)\n        ', max_length=30, null=True),
        ),
    ]
