# Generated by Django 5.0.2 on 2024-03-25 17:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_standardblockpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardblockpage',
            name='summary',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
