# Generated by Django 5.1 on 2024-10-18 19:02

import advanced_forms.models
import core.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_standardblockpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardblockpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("read_more", 1),
                    ("show_featured_image", 2),
                    ("page_feature", 3),
                    ("expandable_list", 4),
                    ("embed", 5),
                    ("auto_index", 6),
                    ("selectable_index", 8),
                    ("document_list", 9),
                    ("badge_area", 10),
                    ("anchor", 12),
                    ("upcoming_service", 13),
                    ("upcoming_oos", 14),
                    ("multi_column", 16),
                    ("directions", 19),
                    ("page_tree_index", 8),
                    ("advanced_form", 20),
                    ("card_container", 23),
                    ("section", 29),
                    ("table_of_contents", 30),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("core.blocks.ReadMoreTagBlock", (), {}),
                    2: ("core.blocks.ShowFeaturedImageBlock", (), {}),
                    3: ("core.blocks.PageFeatureBlock", (), {}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (core.blocks.ExpandableListItemBlock,),
                        {},
                    ),
                    5: ("wagtail.embeds.blocks.EmbedBlock", (), {"max_height": 900}),
                    6: ("core.blocks.AutoIndexBlock", (), {}),
                    7: ("wagtail.blocks.PageChooserBlock", (), {}),
                    8: ("wagtail.blocks.StructBlock", [[("page", 7)]], {}),
                    9: ("core.blocks.DocumentListBlock", (), {}),
                    10: ("core.blocks.BadgeAreaBlock", (), {"child_block": 13}),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: ("wagtail.blocks.StructBlock", [[("name", 11)]], {}),
                    13: ("core.blocks.UpcomingServiceBlock", (), {}),
                    14: ("core.blocks.UpcomingOrderOfServiceBlock", (), {}),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0)]],
                        {"max_num": 3},
                    ),
                    16: ("wagtail.blocks.StreamBlock", [[("column", 15)]], {}),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Image associated with step in directions",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("body", 0), ("image", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.StreamBlock", [[("step", 18)]], {}),
                    20: (
                        "core.blocks.AdvancedFormBlock",
                        (advanced_forms.models.AdvancedForm,),
                        {},
                    ),
                    21: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("body", 0),
                                ("image", 21),
                                ("action_text", 11),
                                ("action_link", 11),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.StreamBlock", [[("card", 22)]], {}),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 0),
                                ("read_more", 1),
                                ("show_featured_image", 2),
                                ("page_feature", 3),
                                ("expandable_list", 4),
                                ("embed", 5),
                                ("auto_index", 6),
                                ("selectable_index", 8),
                                ("document_list", 9),
                                ("badge_area", 10),
                                ("anchor", 12),
                                ("upcoming_service", 13),
                                ("upcoming_oos", 14),
                                ("multi_column", 16),
                                ("directions", 19),
                                ("page_tree_index", 8),
                                ("advanced_form", 20),
                                ("card_container", 23),
                            ]
                        ],
                        {"required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 11), ("body", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 0),
                                ("read_more", 1),
                                ("show_featured_image", 2),
                                ("page_feature", 3),
                                ("expandable_list", 4),
                                ("embed", 5),
                                ("auto_index", 6),
                                ("selectable_index", 8),
                                ("document_list", 9),
                                ("badge_area", 10),
                                ("anchor", 12),
                                ("upcoming_service", 13),
                                ("upcoming_oos", 14),
                                ("multi_column", 16),
                                ("directions", 19),
                                ("page_tree_index", 8),
                                ("advanced_form", 20),
                                ("card_container", 23),
                                ("sub_sub_section", 25),
                            ]
                        ],
                        {"required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 11), ("body", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 0),
                                ("read_more", 1),
                                ("show_featured_image", 2),
                                ("page_feature", 3),
                                ("expandable_list", 4),
                                ("embed", 5),
                                ("auto_index", 6),
                                ("selectable_index", 8),
                                ("document_list", 9),
                                ("badge_area", 10),
                                ("anchor", 12),
                                ("upcoming_service", 13),
                                ("upcoming_oos", 14),
                                ("multi_column", 16),
                                ("directions", 19),
                                ("page_tree_index", 8),
                                ("advanced_form", 20),
                                ("card_container", 23),
                                ("sub_section", 27),
                            ]
                        ],
                        {"required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 11), ("body", 28)]],
                        {},
                    ),
                    30: ("core.blocks.TableOfContentsBlock", (), {}),
                },
                null=True,
            ),
        ),
    ]
