# Generated by Django 5.1 on 2024-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_standardblockpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpage",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Subject"),
        ),
    ]
