# Generated by Django 5.2.5 on 2025-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_standardblockpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='show_sidebar',
            field=models.BooleanField(default=False, help_text='\n        If checked, the standard sibling page listing sidebar will be shown on this page.\n        '),
        ),
    ]
