# Generated by Django 6.0.3 on 2026-03-18 18:35

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_standardblockpage_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='accent_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default=None, help_text='Accent color for this page. If set, overrides the global accent color for this page.', max_length=7, null=True),
        ),
    ]
