# Generated by Django 4.1.6 on 2023-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagecarouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='header',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
