# Generated by Django 4.1.6 on 2023-03-06 21:31

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecard',
            name='body',
            field=wagtail.fields.RichTextField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecard',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
