# Generated by Django 4.1.6 on 2023-03-06 22:13

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagecard_body_homepagecard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecard',
            name='action_text',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecard',
            name='action_url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagecard',
            name='body',
            field=wagtail.fields.RichTextField(max_length=400),
        ),
    ]
