# Generated by Django 4.2.1 on 2023-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepagecard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecard',
            name='action_text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='homepagecard',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
