# Generated by Django 4.2.1 on 2023-05-08 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepagecard_action_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='display_next_events',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='upcoming_events',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='upcoming_events_last_checked',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 5, 44, 38, tzinfo=datetime.timezone.utc)),
        ),
    ]
