# Generated by Django 4.2.1 on 2023-05-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0013_homepage_first_time_visitors_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='live_stream_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
