# Generated by Django 4.2.1 on 2023-06-03 20:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepagebadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebadge',
            name='text',
            field=wagtail.fields.RichTextField(max_length=100, null=True),
        ),
    ]
