# Generated by Django 5.0.2 on 2024-03-13 18:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepagebadge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='center_stage_body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='center_stage_header_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
