# Generated by Django 5.1 on 2025-02-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_homepage_center_stage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="show_upcoming_events",
            field=models.BooleanField(
                default=True, help_text='Show "Upcoming Events" card using legacy hacks'
            ),
        ),
    ]
