# Generated by Django 5.1 on 2025-02-28 16:47

import planningcenter_events.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_homepage_show_upcoming_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("card_container", 4), ("badge_area", 7), ("event_listing", 8)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("body", 1),
                                ("image", 2),
                                ("action_text", 0),
                                ("action_link", 0),
                            ]
                        ],
                        {},
                    ),
                    4: ("wagtail.blocks.StreamBlock", [[("card", 3)]], {}),
                    5: ("wagtail.blocks.URLBlock", (), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("link", 5), ("link_text", 0)]],
                        {},
                    ),
                    7: ("core.blocks.BadgeAreaBlock", (6,), {}),
                    8: (
                        "planningcenter_events.blocks.EventListingBlock",
                        (planningcenter_events.models.EventListing,),
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
