# Generated by Django 5.1 on 2025-03-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="display_next_events",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="show_upcoming_events",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="upcoming_events",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="upcoming_events_last_checked",
        ),
    ]
