# Generated by Django 5.1 on 2025-03-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_remove_homepage_display_next_events_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePageBadge",
        ),
    ]
