# Generated by Django 5.1 on 2025-03-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_delete_homepagebadge"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePageCard",
        ),
    ]
