# Generated by Django 5.1 on 2025-03-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_delete_homepagecard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="live_stream_page",
        ),
    ]
