# Generated by Django 5.1 on 2025-03-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_remove_homepage_live_stream_page"),
        ("services", "0030_remove_servicepage_vimeo_link"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="first_time_visitors_page",
            field=models.ForeignKey(
                blank=True,
                help_text='Page to link to the "First Time Visitor?" button below the upcoming service',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name='"First Time Visitors" page',
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_home_page",
            field=models.OneToOneField(
                blank=True,
                help_text='Page to link to the "All Services" button below the upcoming service.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="services.serviceshomepage",
                verbose_name="Services home page",
            ),
        ),
    ]
