# Generated by Django 6.0.3 on 2026-03-17 16:21

import advanced_forms.models
import planningcenter_events.models
import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('card_container', 36), ('badge_area', 14), ('event_listing', 37)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1), ('image', 2), ('action_text', 0), ('action_link', 0)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Show More'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Show Less'}), 6: ('core.blocks.PageFeatureBlock', (), {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'max_height': 900}), 8: ('core.blocks.AutoIndexBlock', (), {}), 9: ('wagtail.blocks.PageChooserBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('page', 9)]], {}), 11: ('core.blocks.DocumentListBlock', (), {}), 12: ('wagtail.blocks.URLBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('image', 2), ('link', 12), ('link_text', 0)]], {}), 14: ('core.blocks.BadgeAreaBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('name', 0)]], {}), 16: ('core.blocks.UpcomingServiceBlock', (), {}), 17: ('core.blocks.UpcomingOrderOfServiceBlock', (), {}), 18: ('wagtail.blocks.StreamBlock', [[('rich_text', 1)]], {'max_num': 3}), 19: ('wagtail.blocks.StreamBlock', [[('column', 18)]], {}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image associated with step in directions', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1), ('image', 20)]], {}), 22: ('wagtail.blocks.StreamBlock', [[('step', 21)]], {}), 23: ('core.blocks.AdvancedFormBlock', (advanced_forms.models.AdvancedForm,), {}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 25: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 26: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 28: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 29: ('wagtail.blocks.EmailBlock', (), {'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 31: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 32: ('wagtail.blocks.StructBlock', [[('link_to', 24), ('page', 25), ('file', 26), ('custom_url', 27), ('anchor', 28), ('email', 29), ('phone', 30), ('new_window', 31)]], {}), 33: ('wagtail.blocks.StructBlock', [[('link', 32), ('link_text', 0)]], {}), 34: ('wagtail.blocks.StreamBlock', [[('rich_text', 1), ('page_feature', 6), ('embed', 7), ('auto_index', 8), ('selectable_index', 10), ('document_list', 11), ('badge_area', 14), ('anchor', 15), ('upcoming_service', 16), ('upcoming_oos', 17), ('multi_column', 19), ('directions', 22), ('page_tree_index', 10), ('advanced_form', 23), ('button_block', 33)]], {}), 35: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1), ('image', 2), ('expand_action_text', 4), ('contract_action_text', 5), ('expanded_content', 34)]], {}), 36: ('wagtail.blocks.StreamBlock', [[('card', 3), ('expandable_card', 35)]], {}), 37: ('planningcenter_events.blocks.EventListingBlock', (planningcenter_events.models.EventListing,), {})}, null=True),
        ),
    ]
