# Generated by Django 4.1.6 on 2023-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitewidesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
