# Generated by Django 4.1.6 on 2023-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitewidesettings_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesettings',
            name='churchcenter_calendar_url',
            field=models.CharField(blank=True, help_text='Church Center Calendar URL', max_length=900, null=True),
        ),
    ]
