# Generated by Django 4.1.6 on 2023-03-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitewidesettings_livestream_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitewidesettings',
            name='site',
        ),
    ]
