# Generated by Django 4.1.6 on 2023-03-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_sitewidesettings_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesettings',
            name='directions_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sitewidesettings',
            name='giving_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitewidesettings',
            name='header_announcement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
