# Generated by Django 4.1.6 on 2023-05-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_genericindexpage'),
        ('site_settings', '0007_alter_sitewidesettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minister_feature_heading', models.CharField(max_length=50)),
                ('minister_feature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pagewithposts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
