# Generated by Django 4.1.6 on 2023-05-02 19:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_footersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='additional_content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=True),
        ),
    ]
