# Generated by Django 4.2.1 on 2023-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_footersettings_additional_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesettings',
            name='refresh_from_planningcenter_every',
            field=models.IntegerField(default=5),
        ),
    ]
