# Generated by Django 4.2.1 on 2023-05-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('site_settings', '0010_sitewidesettings_refresh_from_planningcenter_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesettings',
            name='internal_livestream_page_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
