# Generated by Django 4.2.1 on 2023-05-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_sitewidesettings_internal_livestream_page_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitewidesettings',
            old_name='internal_livestream_page_url',
            new_name='internal_livestream_page',
        ),
    ]
