# Generated by Django 4.2.1 on 2023-06-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_rename_internal_livestream_page_url_sitewidesettings_internal_livestream_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('settings_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_links', to='site_settings.sitewidesettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
