# Generated by Django 4.2.1 on 2023-06-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_headerlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderLink',
        ),
    ]
