# Generated by Django 4.2.1 on 2023-06-09 19:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_delete_headerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesettings',
            name='header_links',
            field=wagtail.fields.StreamField([('url', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('destination', wagtail.blocks.CharBlock())], icon='globe'))], null=True, use_json_field=True),
        ),
    ]
