# Generated by Django 4.2.1 on 2023-06-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_sitewidesettings_header_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitewidesettings',
            name='directions_url',
        ),
        migrations.RemoveField(
            model_name='sitewidesettings',
            name='giving_url',
        ),
    ]
