# Generated by Django 4.2.1 on 2023-08-28 14:24

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0016_remove_sitewidesettings_directions_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='additional_content',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='minister_feature',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='minister_feature_heading',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='content',
            field=wagtail.fields.StreamField([('footer_text', wagtail.blocks.CharBlock(max_length=60))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_notice',
            field=models.CharField(blank=True, help_text='Copyright Notice - displayed in footer', max_length=70, null=True),
        ),
    ]
