# Generated by Django 4.2.1 on 2023-08-28 14:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0017_remove_footersettings_additional_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='content',
            field=wagtail.fields.StreamField([('footer_text', wagtail.blocks.RichTextBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
