# Generated by Django 5.0.2 on 2024-02-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0018_alter_footersettings_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesettings',
            name='emergency_alert',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
