# Generated by Django 5.1 on 2024-11-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0019_sitewidesettings_emergency_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewidesettings",
            name="shynet_ingress_url",
            field=models.CharField(
                blank=True,
                help_text="The first part of the shynet ingress URL - leave off the filename.",
                max_length=900,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitewidesettings",
            name="use_shynet",
            field=models.BooleanField(default=False),
        ),
    ]
