# Generated by Django 5.1.4 on 2025-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0020_sitewidesettings_shynet_ingress_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesettings',
            name='max_fetched_planning_center_events',
            field=models.PositiveSmallIntegerField(default=200, help_text='Maximum number of calendar events to fetch from Planning Center at a time'),
        ),
    ]
