# Generated by Django 5.1 on 2025-03-03 20:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0022_alter_sitewidesettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewidesettings",
            name="copyright_notice",
            field=models.CharField(
                blank=True,
                help_text="Displayed below footer content.",
                max_length=70,
                null=True,
                verbose_name="Copyright Notice",
            ),
        ),
        migrations.AddField(
            model_name="sitewidesettings",
            name="footer_content",
            field=wagtail.fields.StreamField(
                [("footer_text", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})},
                help_text="Each of these blocks should ideally be quite short single lines. These are displayed in a row across the site footer.",
                null=True,
                verbose_name="Footer Content",
            ),
        ),
    ]
