# Generated by Django 5.2.3 on 2025-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0024_delete_footersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewidesettings",
            name="search_maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="When checked, disables the search page and shows a maintenance message in its place.",
            ),
        ),
    ]
