# Generated by Django 5.2.3 on 2025-09-24 13:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0025_sitewidesettings_search_maintenance_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewidesettings",
            name="search_maintenance_message",
            field=wagtail.fields.RichTextField(
                default="The search function is currently down for routine server maintenance. Please come back later.",
                help_text="Message to be displayed in place of the usual search page",
                verbose_name="Search Maintenance Message",
            ),
        ),
        migrations.AlterField(
            model_name="sitewidesettings",
            name="search_maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="When checked, disables the search page and shows a maintenance message in its place.",
                verbose_name="Search Maintenance Mode",
            ),
        ),
    ]
