# Generated by Django 4.1.6 on 2023-03-03 20:51

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupshomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupshomepage',
            name='body',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
