# Generated by Django 4.1.6 on 2023-03-07 23:07

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupshomepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppage',
            name='parent',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='group.groupshomepage'),
        ),
    ]
