# Generated by Django 4.1.6 on 2023-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_grouppage_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppage',
            name='parent',
        ),
    ]
