# Generated by Django 4.1.6 on 2023-03-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_groupshomepagetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupsHomePageTest',
        ),
    ]
