# Generated by Django 4.1.6 on 2023-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_delete_groupshomepagetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppage',
            name='show_posts',
            field=models.BooleanField(default=True),
        ),
    ]
