# Generated by Django 4.2.1 on 2023-06-01 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_grouppage_group_type_grouppage_last_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppage',
            name='last_fetched',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 5, 44, 38, tzinfo=datetime.timezone.utc)),
        ),
    ]
