# Generated by Django 4.2.1 on 2023-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_alter_grouppage_last_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppage',
            name='group_info',
            field=models.BinaryField(null=True),
        ),
    ]
