# Generated by Django 4.2.1 on 2023-06-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_grouppage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppage',
            name='body',
        ),
    ]
