# Generated by Django 5.0 on 2024-01-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_grouppage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppage',
            name='body',
        ),
    ]
