# Generated by Django 5.0 on 2024-01-07 02:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_remove_grouppage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppage',
            name='summary',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
    ]
