# Generated by Django 5.1 on 2024-12-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0017_alter_grouppage_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppage",
            name="group_is_open",
            field=models.BooleanField(default=True),
        ),
    ]
